apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-argo-ccp-bucket1-testing
spec:
  forProvider:
    region: us-east-1
    tags:
      project: CCP
      env: dev
      aws: eks
  providerConfigRef:
    name: newawsconfig
